name: Release Manager

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  SBML_to_Discord:
    env: 
      DISCORD_WEBHOOK_RELEASE: ${{secrets.DISCORD_WEBHOOK_RELEASE}}
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Model
      run: |
        python .github/tests/tsv_to_sbml.py
    - name: Report to Discord server
      run: |
        tar -czvf WormJam.tar.gz WormJam.xml
        python .github/tests/release_manager.py "$DISCORD_WEBHOOK_RELEASE" $GITHUB_REPOSITORY $GITHUB_REF

